### ISSUE TITLE
Create express interest/signup form

### ISSUE THREAD

**Issue by csexton** [rubyforgood/rubyforgood.org--old#1]
Perhaps simply a google doc with a form.

It should have the following:
- [x] name
- [x] email
- [x] willingness to lead a team
- [x] basic skills (dev/design/ops/hugs)
- [x] project proposal for good*

\* Not sure if this should be on a separate form, but seems good to gather in advance.

**Comment by seanmarcia** [comment]
We definitely need the proposals in advance. I thought that was what we could use the uservoice account I setup for. Let people suggest and vote on proposals there.

I think we need to be fairly deliberate in the choice of team leads... Back in 2011 when I was new to ruby/rails I took part in a hackfests for social justice organized by Greg Brown and Jordan Byron. I recently looked at the project for inspiration and I noticed that the lead of the project created several issues/tasks that probably took as much time for him to type out that it would have taken him to code but I realize now, in retrospect, that he created those so that I, and the other ruby newbie could feel useful.
