### ISSUE TITLE
Setup GoFundMe style of account for year long opportunities for donations

### ISSUE THREAD

**Issue by kalimar** [rubyforgood/rubyforgood.org--old#72]
After we have figured out the right bank account to use we can:
- [ ] Create a GoFundMe or similar style of account for Ruby For Good
- [ ] Add link on Sponsors page to Patreon account.

**Comment by spinecone** [comment]
Here's an example of another potential donate service thing https://www.crowdrise.com/dance-across-the-usa/fundraiser/

**Comment by spinecone** [comment]
A different option, this one supports one time and recurring donations: https://www.globalgiving.org/projects/science-workshop-for-30-poor-children-cape-town/

**Comment by juliancheal** [comment]
![nph-elmo-dance](https://cloud.githubusercontent.com/assets/63991/16173257/71edc6a8-3569-11e6-8eff-9e6c760033d4.gif)

**Comment by spinecone** [comment]
I compared a few different options, and CrowdRise looks like the best choice for raising small, one-time donations for Ruby for Good. Donations go directly to the organization, and they won't be taxed ("the vast majority of donations on CrowdRise are considered to be ‘Personal Gifts” and are not taxed as income in the US"). They take 5% of all donations which sounds reasonable.

It's probably best to wait for 5013c to be figured out before registering with them since they'll need detailed information about the organization to set up billing. More information is here: https://support.crowdrise.com/hc/en-us/categories/200101590-Non-Profits-on-CrowdRise

**Comment by spinecone** [comment]
a fine spot for a "donate to us!" button 🍰 
![screen shot 2016-06-19 at 10 52 12 am](https://cloud.githubusercontent.com/assets/7772827/16178026/f224c11c-360b-11e6-9fa3-c0adc6d0da63.png)

**Comment by craig-riecke** [comment]
Has there been a political decision on this?  There's currently a place to donate small amounts of money on the web site, so ... maybe it's done?
